### ISSUE TITLE
00xWizard - Missing Recipient Parameter Leading to Funds Transfer Failure

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-axis-finance-judging#1]
00xWizard

high

# Missing Recipient Parameter Leading to Funds Transfer Failure

## Summary
 The `recipient` parameter is missing in the `BidParams` struct, leading to the inability to specify an address to receive the payout during an auction.

## Vulnerability Detail

The `BidParams` struct has mentioned a `recipient` address which is used to receive payout, however in the struct implementation, the `recipient` parameter is missing, Without the recipient parameter, the auction's `bid` function will use the struct and it will not have the necessary information to deliver the funds to the intended recipient. As a result, the auction process will fail to complete as expected, leading to an inability to transfer the payout to the rightful recipient.

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L55

## Impact

 failure to deliver the funds to the intended recipient due to missing `recipient` parameter.

## Code Snippet
```javascript
    /// @notice     Parameters used by the bid function
    /// @dev        This reduces the number of variables in scope for the bid function
    ///
    /// @param      lotId               Lot ID
    /// @param      recipient           Address to receive payout
    /// @param      referrer            Address of referrer
    /// @param      amount              Amount of quoteToken to purchase with (in native decimals)
    /// @param      auctionData         Custom data used by the auction module
    /// @param      permit2Data_        Permit2 approval for the quoteToken (abi-encoded Permit2Approval struct)
    struct BidParams {
        //@audit missing recipient address
        uint96 lotId;
        address referrer;
        uint96 amount;
        bytes auctionData;
        bytes permit2Data;
    }
```
## Tool used

Manual Review

## Recommendation
 add the `recipient` parameter. This will ensure that there is a designated address to receive the payout during the auction process.

```javascript
    /// @notice     Parameters used by the bid function
    /// @dev        This reduces the number of variables in scope for the bid function
    ///
    /// @param      lotId               Lot ID
    /// @param      recipient           Address to receive payout
    /// @param      referrer            Address of referrer
    /// @param      amount              Amount of quoteToken to purchase with (in native decimals)
    /// @param      auctionData         Custom data used by the auction module
    /// @param      permit2Data_        Permit2 approval for the quoteToken (abi-encoded Permit2Approval struct)
    struct BidParams {
        //@audit missing recipient address
        uint96 lotId;
  ++   address recipient;
        address referrer;
        uint96 amount;
        bytes auctionData;
        bytes permit2Data;
    }
```

**Comment by 00xWizard** [comment]
Fair enough, will keep moving forward. Thanks for the quick judging
