### ISSUE TITLE
MrjoryStewartBaxter - Funds can be stuck in a contract if a bid is submitted by a USDC/USDT bidder who is blacklisted.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-axis-finance-judging#10]
MrjoryStewartBaxter

high

# Funds can be stuck in a contract if a bid is submitted by a USDC/USDT bidder who is blacklisted.

## Summary

USDC/USDT tokens have implemented an administratively owned blocklist feature effectively restricting users from transmitting or acquiring funds. This is important to consider as these tokens are not specifically constrained for the protocol such as fee on transfer/deflationary/rebase tokens (clarified in the Context Q&A), hence it is assumed as a potential issue for the auctions.

## Vulnerability Detail

Note that https://github.com/d-xo/weird-erc20#tokens-with-blocklists shows that:

Some tokens (e.g. USDC, USDT) have a contract level admin controlled address blocklist. If an address is blocked, then transfers to and from that address are forbidden.

The following scenario describes the problem:

1. Bidder submits a bid while not included in the token blacklist. 
2. Subsequently, after placing the bid, Bidder is added to the token blacklist. 
3. Bidder cancels the bid and triggers a refund; however the refund transaction fails due to Bidder's inclusion in the blacklist, impeding the transfer of tokens back. 

or directly:

A blacklisted USDC user place a bid. When auction is finished it reverts as the blacklisted user transfer is forbidden. The bid will be stuck in the contract.

## Code Snippet

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L340-L373 // For ex. bid function does not validate if bid is valid with blacklisted tokens, moreover, 

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/bases/Auctioneer.sol#L160-L186
// auction function currently checks if base token and quote token are non zero address and if the base token or quote token decimals are not within the required range. There is no validation regarding tokens with blocklist present. 

## Impact

Due to the lack of verification for the bidders presence on the blocklist, the contract might be unable to distribute funds. This translates on bidders not able to cancel a bid effectively and potentially their funds being stuck. 

## Tool used

Manual Review

## Recommendation

A possible solution to address this vulnerability is to implement a validation, (possibly within the refundBid() and claimBid() functions), specifically verifying whether the bidder is not blacklisted before returning the funds. 

Another possibility relies on handling this special token directly within the bid() function, for example implementing specific logic determining if the bid is correct while checking if the token for the bid uses a blocklist, then the bid might be invalid (depending on how the protocol team would handle this blocklisted tokens):

```solidity
 // The module will determine if the bid is valid - minimum bid size, minimum price, auction status, etc
        bidId = _getModuleForId(params_.lotId).bid(
            params_.lotId, msg.sender, params_.referrer, params_.amount, params_.auctionData
        );
```

Alternatively in `claimBids` and `refundBids` functions consider adding a try catch block for the transfer call.

**Comment by fvelazquez-X** [comment]
Escalate

Good day. Please I kindly request to review this finding again,. It is as these ones:

https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/100 
https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/138
https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/149
 
etc..

For example in finding 100 (extracting the main details of the issue present):

"Settling a batch auction might become impossible if a partially filled bidder or the curator gets blacklisted in either the base or quote tokens. In such scenarios, the seller and other bidders won't receive their payments (payouts or refunds), resulting in funds being locked within the AuctionHouse contract"

In my finding:

"A blacklisted USDC user place a bid. When auction is finished it reverts as the blacklisted user transfer is forbidden. The bid will be stuck in the contract"

I have examined the other duplicates and believe that my findings align with theirs. In any case, if the judge potentially required more information (input requested) it could have been done via the communication channels. Nevertheless, my finding is consistent with the accepted issues. Please I kindly ask a review. 

Thank you very much and
Kind Regards,

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Good day. Please I kindly request to review this finding again,. It is as these ones:
> 
> https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/100 
> https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/138
> https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/149
>  
> etc..
> 
> For example in finding 100 (extracting the main details of the issue present):
> 
> "Settling a batch auction might become impossible if a partially filled bidder or the curator gets blacklisted in either the base or quote tokens. In such scenarios, the seller and other bidders won't receive their payments (payouts or refunds), resulting in funds being locked within the AuctionHouse contract"
> 
> In my finding:
> 
> "A blacklisted USDC user place a bid. When auction is finished it reverts as the blacklisted user transfer is forbidden. The bid will be stuck in the contract"
> 
> I have examined the other duplicates and believe that my findings align with theirs. In any case, if the judge potentially required more information (input requested) it could have been done via the communication channels. Nevertheless, my finding is consistent with the accepted issues. Please I kindly ask a review. 
> 
> Thank you very much and
> Kind Regards, 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@fvelazquez-X Your original submission did not highlight how blacklist will affect other users other than the bidder itself, so I believe the sherlock rule applies to your submission.

**Comment by fvelazquez-X** [comment]
Hello @nevillehuang , finding #138 is also talking about only the bidder itself throughout the finding and it was valid. 

But honestly I dont get why this is talking about "self" it is a clear scenario where 1 or more bidders can get blacklisted its evidently a flaw even if you talk about only on the bidder side, there is no doubt. Honestly it looks just a matter of semantics that my finding is not valid which is completely unfair because it is exactly the same issue as the valid ones, but totally. Pointing the scenario only to the bidders is perfectly enough to highlight the issue, I dont know why the appreciation and flexbility is so hard here, overalls because anyway bidders are one of the main entities of the auction. 

I kindly ask to validate this finding.

**Comment by nevillehuang** [comment]
@fvelazquez-X I suggest to reread impact and issue #138 as a whole, this will be my last comment here, I will leave escalation resolution to @Czar102, and stand by my decision

> All base and quote tokens are stuck due to a blacklisted partially filled bidder or curator

**Comment by fvelazquez-X** [comment]
Thanks @nevillehuang for your input. 

I read it as whole. There is no reason for invalidation. Even if I just pointed out bidders, the think about only affecting "self"  does not mean my finding in invalid specially after the auction has bidders as one of the main actors of the process, and also considering this finding #138  explained the issue mostly with bidders. 

Regards,

**Comment by Evert0x** [comment]
Planning to reject escalation and keep issue state as is

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [fvelazquez-x](https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/10/#issuecomment-2045576658): rejected
