### ISSUE TITLE
cu5t0mPe0 - user can't refund After cancel Auction

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-axis-finance-judging#121]
cu5t0mPe0

high

# user can't refund After cancel Auction

## Summary

Users are unable to receive the amount due to changes in the status of the auction.

## Vulnerability Detail

The user wants to exit the auction during the auction call refund function

in refund process:

Check if the current auction has ended

https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/modules/Auction.sol#L501-L516

https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/modules/Auction.sol#L731-L741

However, if a malicious seller directly calls the cancel function to cancel the auction, the user will not be able to refund because the current auction status is already over.

https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/modules/Auction.sol#L340-L364

## Impact

User cannot refunds

## Code Snippet

https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/modules/Auction.sol#L340-L364

## Tool used

Manual Review

## Recommendation

Try adding a pre-cancel state where deposits are no longer allowed, allowing users to take refunds, or add a cancel state, where auctions in the canceled state allow refunds

Duplicate of #67

**Comment by 0xJem** [comment]
It's hard to decipher, but I think it's a duplicate of #67
