### ISSUE TITLE
cryptic - EMPAM and FPAM auction modules do not implement catalogue functions

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-axis-finance-judging#130]
cryptic

high

# EMPAM and FPAM auction modules do not implement catalogue functions

## Summary
The `Catalogue.sol` contract contains view functions which provide important information for auctions. These include functions that provide estimates regarding the payout a user will receive for a payment amount, the payment they must send to receive a specific payout, etc. These functions are expected to be implemented by the auction modules. However, `EMPAM.sol` (batch auction module) and `FPAM.sol` (atomic auction module) do not implement these functionalities. This will cause a permanent DoS of the core functionalities of the catalogue contract for these modules and users will not be able to view any information regarding auctions created using either modules and the payments associated with them.

## Vulnerability Detail
`EMPA.md` states the following (location: /design/EMPA.md):

```solidity
We will provide a user interface (aka dApp) for both Sellers and Buyers to interact with the product. The key user actions are defined below in the Actions section. The core pages we be:
- List of auctions (TBD on design and filtering between statuses)
- Create auction page - for sellers to create new auctions
- Auction page - Details the status and available actions for a given auction. The auction page will need to support these differents states:
  - Created - Auction has been created, but not started
  - Live - Auction is created and currently accepting bids. Buyers should be able to bid and cancel bids they have made.
  - Concluded - Auction has ended and bids are being decrypted. Anyone should be able to decrypt the bids and submit them to the contract for verification.
  - Decrypted - Bids are decrypted and awaiting settlement. Anyone should be able to settle the auction.
  - Settled - Auction payouts have been issued. Buyers that did not win can claim refunds.
```

Although buyers can view the list of auctions in the provided UI, there's no indication that they can view information regarding prices, which is why the catalogue contract is very important for buyers. They can estimate what price to pay, in quote tokens to receive a specific amount of base tokens, and vice versa. Lets look at exactly which functions will suffer from DoS and why.

`Catalogue::payoutFor`
```javascript
    function payoutFor(uint96 lotId_, uint96 amount_) external view returns (uint256) {
        Auction module = Auctioneer(auctionHouse).getModuleForId(lotId_);
        Auctioneer.Routing memory routing = getRouting(lotId_);

        // Get protocol fee from FeeManager
        // TODO depending on whether this is a purchase or a bid, we should use different fee sources
        (uint48 protocolFee, uint48 referrerFee,) =
            FeeManager(auctionHouse).fees(keycodeFromVeecode(routing.auctionReference));

        // Calculate fees
        (uint256 toProtocol, uint256 toReferrer) =
            FeeManager(auctionHouse).calculateQuoteFees(protocolFee, referrerFee, true, amount_); // we assume there is a referrer to give a conservative amount

        // Get payout from module
@>      return module.payoutFor(lotId_, amount_ - uint96(toProtocol) - uint96(toReferrer));
    }
```

In this function, the user can pass in the id for a lot with the amount of quote tokens they would like to pay. They expect to receive the amount of base tokens they will get for that payment. After deducting fees from the payment, a call to `AuctionModule::payoutFor` is made.

`AuctionModule::payoutFor`
```javascript
    function payoutFor(uint96 lotId_, uint96 amount_) public view virtual returns (uint96) {}
```

The function is expected to be implemented by the auction module (this was also confirmed with the developer team on discord). So far there are two auction modules implemented, `EMPAM.sol` (batch auction module) and `FPAM.sol` (atomic auction module). Sellers can create new auctions within these modules, but they cannot create new modules due to access control.

Looking at `EMPAM.sol` and `FPAM.sol`, neither auctions implement `payoutFor`. When users attempt to call this function, it will revert, and users will be unable to estimate payouts and cannot assess/accomodate their purchases in advance, indefinitely. In addition to `payoutFor`, the following will also suffer from permanent DoS because they are not implemented in either auction modules:

`priceFor`: Users will not be able to estimate the price (including fees, etc) for a specific payout
`maxPayout`: Users will not be able to check the max payout they may receive for an auction
`maxAmountAccepted`: Users will not be able to check the max amount of quote tokens accepted for an auction

## Impact
Permanent DoS of the core functionalities of the Catalogue contract. Buyers will not be able to view information of auctions, especially regarding the prices, which will cause massive hindrance and confusion for buyers. It is very likely that many potential buyers will simply opt-out of participating in these auctions, which will lead to sellers not participating, and overall loss for Axis Finance.

## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/Catalogue.sol#L72

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/Auction.sol#L235

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol#L13

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/FPAM.sol#L12

## Tool used
Manual Review

## Recommendation
Implement the functions above for both batch (EMPAM) and atomic (FPAM) auctions, so buyers can interact with the catalogue.

**Comment by AtanasDimulski** [comment]
Escalate,

This report describes view functions utilized by the front end of the application not returning correct information. The functions specified in this report are not used in the protocol in any other way and thus don't break any core functionality or lead to a loss of funds. As per sherlock [rules](https://docs.sherlock.xyz/audits/judging/judging#viii.-list-of-issue-categories-that-are-considered-valid):
```
16. Incorrect values in View functions are by default considered low.
Exception: In case any of these incorrect values returned by the view functions are used as a part of a larger function which would result in loss of funds then it would be a valid medium/high depending on the impact.
```

This issue should be low.

**Comment by sherlock-admin2** [comment]
> Escalate,
> 
> This report describes view functions utilized by the front end of the application not returning correct information. The functions specified in this report are not used in the protocol in any other way and thus don't break any core functionality or lead to a loss of funds. As per sherlock [rules](https://docs.sherlock.xyz/audits/judging/judging#viii.-list-of-issue-categories-that-are-considered-valid):
> ```
> 16. Incorrect values in View functions are by default considered low.
> Exception: In case any of these incorrect values returned by the view functions are used as a part of a larger function which would result in loss of funds then it would be a valid medium/high depending on the impact.
> ```
> 
> This issue should be low. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@AtanasDimulski While I agree it only affects view function, it does render almost the whole `Catalogue.sol` contract in scope useless though, thats why i validated it. If not, this contract should have been excluded from scope in the first place. So this comes down to who interpreted the rules right, where in this case, there is no incorrect return values, but rather almost the whole contract is non-functional

**Comment by AtanasDimulski** [comment]
@nevillehuang I think the rules are pretty clear, there is no functionality except the three functions mentioned in the above report that is affected by this let alone core functionality. Only three functions regarding price are not working, there is no possibility of sandwich attacks in this protocol, so they are not that important as well.  If you are referring to this [discussion](https://github.com/sherlock-audit/2024-02-telcoin-platform-audit-update-judging/issues/26#issuecomment-2006733734), where the rules for a medium severity issue 
```
Breaks core contract functionality, rendering the contract useless or leading to loss of funds
``` 
are interpreted for a specific contract, I still don't think this should be a medium issue, as these are just view functions and there isn't a real possibility for a loss of funds.

**Comment by nevillehuang** [comment]
I will let @Czar102 decide this one. Don’t have any further comments, but will reiterate that most of the catalogue contract is basically useless.

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Axis-Fi/moonraker/pull/132

**Comment by Evert0x** [comment]
Using the current judging rules, I believe this issue should be invalidated

> **Incorrect values in View functions are by default considered low.**
**Exception:** In case any of these incorrect values returned by the view functions are used as a part of a larger function which would result in loss of funds then it would be a valid medium/high depending on the impact.

Planning to accept escalation and invalidate issue

**Comment by nevillehuang** [comment]
@Evert0x I understand your decision, but I think it would be good to consider removing contracts from scope in the future if only view functions are involved not used anywhere else in the protocol, since it would be a waste of resource for watsons to audit this contract. It also certainly fits the criteria of "rendering the contract useless".

**Comment by AtanasDimulski** [comment]
> @Evert0x I understand your decision, but I think it would be good to consider removing contracts from scope in the future if only view functions are involved not used anywhere else in the protocol, since it would be a waste of resource for watsons to audit this contract. It also certainly fits the criteria of "rendering the contract useless".

I think which contracts are in scope for the audit is up to the protocol team, while it is true that they could have saved a bit of money by not including it, I don't see how this impacts sherlock judging criteria. As for rendering the contract useless, it is a contract used only by the front end(most probably), and the rule about view functions supersedes your argument.

**Comment by nevillehuang** [comment]
@AtanasDimulski I understand your point, just noting down a potential consideration, nothing to do with changing judgements. I think including it in scope certainly helps increase the pot for the benefit of watsons so I could be wrong in this case.

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [AtanasDimulski](https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/130/#issuecomment-2047541712): accepted

**Comment by 10xhash** [comment]
> The protocol team fixed this issue in the following PRs/commits: [Axis-Fi/moonraker#132](https://github.com/Axis-Fi/moonraker/pull/132)

Fixed
Separate catalogues and modules for batch and atomic auctions are made with the respective modules adding the functions

**Comment by sherlock-admin4** [comment]
The Lead Senior Watson signed off on the fix.
