### ISSUE TITLE
thisvishalsingh - Incorrect Settlement Due to Flawed Marginal Price Calculation

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-axis-finance-judging#132]
thisvishalsingh

high

# Incorrect Settlement Due to Flawed Marginal Price Calculation

## Summary
The `_settle` function is vulnerable to a logic flaw in the `_getLotMarginalPrice` function, which may result in an incorrect marginal price, leading to an erroneous settlement.

## Vulnerability Detail
Current Implementation: The `_getLotMarginalPrice` function calculates the marginal price based on decrypted bid amounts and their respective prices.

What Goes Wrong: `If the function encounters bids with prices below the minimum price threshold, it could incorrectly calculate the marginal price, especially if these are the only bids or if they affect the determination of the marginal bid.`
```solidity
function _getLotMarginalPrice(uint96 lotId_)
    internal
    returns (MarginalPriceResult memory result)
{
    // ... existing code ...

    // @audit This is the vulnerable part where the marginal price could be incorrectly determined
    if (price < lotAuctionData.minPrice) {
        result.marginalPrice = lotAuctionData.minPrice;
        // ... more logic ...
    }

    // ... existing code ...
}
```

Other Function Impact: The `_settle` function depends on the marginal price for fund distribution. An incorrect marginal price impacts the settlement's fairness and accuracy.

## Impact
Incorrect fund distribution, leading to potential losses for bidders or the auctioneer.

## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol#L595

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol#L758

## Tool used

Manual Review
[reference link](https://immunefi.com/immunefi-top-10/#v022023-incorrect-calculation)

## Recommendation
- reconsider the logic in  `_getLotMarginalPrice` to handle edge cases where all bids are below the minimum price threshold. 
- Fallback Mechanism: Introduce a mechanism to handle settlement failure gracefully, allowing for manual intervention or automatic refund processes.

**Comment by Oighty** [comment]
There isn't enough information here to examine. If all the bids are below the minimum price and the marginal price is set to the minimum price, then the auction won't clear. Therefore, everyone would just get refunds as expected.
