### ISSUE TITLE
seeques - Callbacks.onCurate() function might not be implemented due to improper validation in Callbacks contract

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-axis-finance-judging#141]
seeques

medium

# Callbacks.onCurate() function might not be implemented due to improper validation in Callbacks contract

## Summary
A seller can provide a Callbacks contract for a batch auction upon auction creation in the `Auctioneer.auction()` function that does not implement the `onCurate()` function. This may result in a broken callbacks integration.
## Vulnerability Detail
The `Auctioneer.auction()` contract checks that the callbacks contract is a valid address by calling `Callbacks.isValidCallbacksAddress()`:
```solidity
if (!Callbacks.isValidCallbacksAddress(routing_.callbacks)) revert InvalidParams();
```
There, the function performs the validation:
```solidity
    function isValidCallbacksAddress(ICallback callbacks) internal pure returns (bool) {
        // Ensure that if the contract is expected to send base tokens, then it implements atleast onCreate and onCurate OR onPurchase (atomic auctions may not be prefunded).
        if (
            callbacks.hasPermission(SEND_BASE_TOKENS_FLAG)
                && (
                    !callbacks.hasPermission(ON_CREATE_FLAG) || !callbacks.hasPermission(ON_CURATE_FLAG)
                ) && !callbacks.hasPermission(ON_PURCHASE_FLAG)
        ) {
            return false;
        }
        ...
 }
```
As the comments state, if the `callbacks.hasPermission(SEND_BASE_TOKENS_FLAG) == true`, then either both `onCurate()` and `onCreate()` functions must be implemented, or just `onPurchase()`. The issue here is that this function does not validate the type of auction being created. In case of a batch auction, a seller could provide Callbacks with implemented `onCreate()` and `onPurchase()` functions and the checks would still pass.
## Impact
Improper validation may result in a broken callbacks integration
## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/lib/Callbacks.sol#L72-L85
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/bases/Auctioneer.sol#L243-L246
## Tool used

Manual Review

## Recommendation
`isValidCallbacksAddress()` should take into account the type of auction the callback are provided for. There is no reason to have `ON_PURCHASE_FLAG` in the callbacks contract for the batch auction type. This can be handled by two separate validation function, each for the given auction type.

**Comment by 0xJem** [comment]
The callbacks contract is selected (and usually developed) by the seller, and it's their responsibility to choose one that works for them (accurate, audited, etc). If the send base tokens flag was true, the auction was prefunded and onCurate was not implemented, then the `curate()` function would revert with the `InvalidCallback` error. This works as intended.
