### ISSUE TITLE
web3tycoon - In `MaxPriorityQueue.sol` the Algorithm does not sort the highest bid correctly.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-axis-finance-judging#150]
web3tycoon

high

# In `MaxPriorityQueue.sol` the Algorithm does not sort the highest bid correctly.

## Summary
When `decrypAndSortBids` is called in  `EMPAM.sol`, it is suppose to sort the bids in decreasing order. well the logic does not implement this. cause it assumes `amountout` of each bid is `equal`, When its different for each bid. 

## Vulnerability Detail

Add this getter functions in  `EMPAM.sol`

```javascript
//  to get max id
     function getmaxId(uint96 lotId_) public view returns (uint96) {
        Queue storage queue = decryptedBids[lotId_];
        uint96 highestBid = queue.getMaxId();
        return highestBid;
    }
// to get number of bids place per bid.
    function getnumOfBids(uint96 lotId_) public view returns (uint256) {
        Queue storage queue = decryptedBids[lotId_];
        uint256 remainingBids = queue.getNumBids();
        return remainingBids;
    }
```
place this unit test  in `decryptAndSortBids.t.sol`
```javascript

 function test_ItSortItCorrectly()
        external
        givenLotIsCreated
        givenLotHasStarted
    {
        uint96 _bidAmount = 1e18;
        uint96 _bidAmountOut = 1e17;
        uint96 _totalAmountBidded; 
        // this is to allow increment the next bidder to have twice the amount of the previous bidder of amount in.
        uint96 _totalAmountBidAmountOut;
        // this is to allow increment the next bidder to have twice the amount of the previous bidder of amount out.

        //lets create 10 bidders and mint them different number of erc20

        for (uint256 i = 1; i <= 10; i++) {
            // we create 10 bidders
            address user = address(uint160(i));
            // update amount in and out to always increase
            uint96 bidAmountIn = _totalAmountBidded + _bidAmount;
            uint96 bidAmountOut = _totalAmountBidAmountOut + _bidAmountOut;
            _createnewBid(user, bidAmountIn, bidAmountOut);
            _totalAmountBidded = bidAmountIn + _totalAmountBidded;
            _totalAmountBidAmountOut = bidAmountOut + _totalAmountBidAmountOut;
        }
        _concludeLot();
        _submitPrivateKey();
        _module.decryptAndSortBids(_lotId, 10);
        // lets get number of bids placed
        uint256 numberOfBids = _module.getnumOfBids(_lotId);
        // we confirm the number of bids are 10
        assertEq(numberOfBids, 10);

        // we expect the heighest bid to be 10 
        uint256 topBid = _module.getmaxId(_lotId);
        // well it should be id number 10 coz it had the highest amount in and amount out
        assertEq(topBid, 10);
        // the sorting say id = 1 is the heighest
        console.log(topBid);
    }

```
we see the highest bid is not 10 as we expected.

## Impact
This will disrupt the functionality of the protocol where the highest bidder, is first to be served, therefore leading to 
`low` bids receiving the `payout` first before highest bidder causing him to loss the auction.

## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/lib/MaxPriorityQueue.sol#L52
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/lib/MaxPriorityQueue.sol#L60
## Tool used
Manual Review

## Recommendation
Add sorting where the logic encapulates amountOut is a differrent number for each bid

**Comment by 0xJem** [comment]
I think the submitter has misunderstood how the queue is sorted - it's not by the amount in or amount out, but the price (amount in/amount out). The test case does not demonstrate that the 10th bid has a higher price than any previous bid.

**Comment by Oighty** [comment]
Agree this is invalid. In the example, you aren't changing the price since you are changing both quantities. All the bids submitted have the same price. Our tiebreaker in that case is the earlier bids take precedence, which is well documented. So bid 1 should be at the top of the queue.
