### ISSUE TITLE
FindEverythingX - Loose checks within isValidCallbackAddress will result in different undesired scenarios and curator fee prevention

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-axis-finance-judging#153]
FindEverythingX

medium

# Loose checks within isValidCallbackAddress will result in different undesired scenarios and curator fee prevention

## Summary
Loose checks within isValidCallbackAddress will result in different undesired scenarios and curator fee prevention

## Vulnerability Detail
Contract: Callback.sol

The isValidCallbacksAddress function is invoked upon auction creation and has a nested condition check which returns false (reverts) if callback hooks are designed in such a way that an auction will not work:

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/lib/Callbacks.sol#L72

In total, there are 13 scenarios where true is returned and 3 scenarios where false is returned (I am only talking about the checks within the if-clause):

[https://github.com/sherlock-audit/2024-03-axis-financeblob/main/moonraker/src/lib/Callbacks.sol#L74]

These checks however, are too loose which means that certain callback addresses are allowed which can result in a DoS. 

To illustrate my point, consider the following scenario:

SEND_BASE_TOKENS_FLAG = true 
ON_CREATE_FLAG = false 
ON_CURATE_FLAG = false 
ON_PURCHASE_FLAG = true

Outcome: Returns true

As we can see, in the following condition scenario, the function does not return false, which means the callback address is valid. 

However, there is a problem: If the auction is marked as “prefunded”, the isValidCallbacksAddress check will pass but the auction can actually never be created because upon creation, no tokens will be transferred in (the onCreate callback is never executed):

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/lib/Callbacks.sol#L115

—----------------------------------------------------------------

Another more severe scenario, which is also the main scenario for that issue being a medium severity:

SEND_BASE_TOKENS_FLAG = true 
ON_CREATE_FLAG = true 
ON_CURATE_FLAG = false 
ON_PURCHASE_FLAG = true 

Outcome: Returns true

In this scenario, assuming the auction is prefunded, the auction creation will work BUT the curator can never invoke curate, because the “onCurate” call will not get executed:

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L675

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/lib/Callbacks.sol#L156

Therefore, no tokens will be transferred in and the balance check reverts:

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L678

This means the seller can intentionally create an auction where the curator can never invoke the curate function. I have already explained the problem with DoS’ing the curate function multiple times in other issues: The curator might have already provided services and maybe also had expenses but cannot invoke curate and therefore will not receive any fees, while the auction creator already benefited from the marketing move.

Another less severe issue:

SEND_BASE_TOKENS_FLAG = true 
ON_CREATE_FLAG = true 
ON_CURATE_FLAG = true 
ON_PURCHASE_FLAG = false 

Outcome: Returns true

If the auction is a non-prefunded FPAM auction, purchase will revert because no tokens are being transferred in due to the lack of ON_PURCHASE_FLAG = false.

There are surely more problems with these condition checks. The root-cause is the absence of:

a) Auction type check
b) Prefunded check

Of course, I need to argue why this is rated as medium severity. In fact, most conditions would only allow for “low” severity. However, the fact that the callback can be set in such a way that the curator will not receive any tokens, surely meets the medium severity criteria.
## Impact
IMPACT:

a) Prevention of curator fee payout.
b) DoS of basic functionalities.

## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/lib/Callbacks.sol#L72

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/lib/Callbacks.sol#L74

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/lib/Callbacks.sol#L115

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L675

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L678

## Tool used

Manual Review

## Recommendation
Consider incorporating checks a) and b) in the condition checks to avoid creating auctions with incorrect callback addresses.

**Comment by 0xJem** [comment]
Duplicate of #141
