### ISSUE TITLE
i3arba - `Auctioneer.sol::auction` is calling `Auctioneer.sol::_onCreateCallback` passing wrong argument

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-axis-finance-judging#16]
i3arba

high

# `Auctioneer.sol::auction` is calling `Auctioneer.sol::_onCreateCallback` passing wrong argument

## Vulnerability Detail
`Auctioneer.sol::auction` is divided into two by an if statement in which the function verifies pre-funding. If `requiresPrefunding == true`, verifies if hasPermission. If it has, call `Auctioneer.sol::_onCreateCallback` passing the correct params. However, if hasPermission is false, the function takes the second path in which regular ERC20 transfer takes place. However, in this second path, `Auctioneer.sol::_onCreateCallback` receives `false` as the last argument instead of true, which this path requires.

## Impact
This creation with wrong parameters will initiate an auction pre-funded as it isn't. This behavior will lead to unexpected responses in several functions and locked pre-funding values.

## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/bases/Auctioneer.sol#L276

## Tool used
Manual Review

## Recommendation

<details>
<summary>Adjust the code as follows</summary>

```diff
...
   else {
            Transfer.transferFrom(
                 routing_.baseToken, msg.sender, address(this), lotCapacity, true
            );
-           _onCreateCallback(routing_, lotId, lotCapacity, false);
+           _onCreateCallback(routing_, lotId, lotCapacity, true);
          }
...
```

</details>

**Comment by 0xJem** [comment]
The `false` parameter in this case indicates that the callback does not need to transfer the tokens. Note that there's a transfer right before it.

**Comment by 0xJem** [comment]
Invalid
