### ISSUE TITLE
MrjoryStewartBaxter - Relevant integrity checks / error handling mechanism are missing when decrypting and sorting bids

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-axis-finance-judging#17]
MrjoryStewartBaxter

medium

# Relevant integrity checks / error handling mechanism are missing when decrypting and sorting bids

## Summary

The function `decryptAndSortBids()` does not verify the integrity of the encrypted bids when iterating over them and performing the decryption process. If a bid was incorrectly encrypted it just skips it upon decryption since there is no error handling mechanism present. 

## Vulnerability Detail

The library `ECIES.sol` implements an elliptic curve algorithm, whose encrypt/decrypt functions are used to process a batch of bids and sort them by price in `EMPAM.sol`. The library implements encryption and decryption mechanisms which are entirely focused on trying to guarantee the secrecy of the message, but once auction settlement phase comes it is also necessary to assure the integrity of the encrypted bids submitted by the participants, something that is missing in the function `_decryptAndSortBids()`.  

Currently, this function iterates through encrypted bids; however, subsequent to decryption, it proceeds to execute validations pertinent to the auction settlement (for example, if the amount out is greater than or equal to the minimum bid size) without incorporating firstly any mechanism to ensure the integrity of the data being decrypted or to failover to some specific action if encrypted data found is corrupted; in other words it omits specific steps if the encryption process executed in the bid returns invalid/corrupted data when decryption occurs. This holds significant importance, particularly in the exchange of data facilitated through both off-chain and on-chain mechanisms during the auction:

```solidity
 for (uint64 i; i < num_; i++) {
            // Load encrypted bid
            uint64 bidId = bidIds[nextDecryptIndex + i];

            // Decrypt the bid
            uint96 amountOut;
            {
                uint256 result = _decrypt(lotId_, bidId, lotBidData.privateKey);

                // Only set the amount out if it is less than or equal to the maximum value of a uint96
                if (result <= type(uint96).max) {
                    amountOut = uint96(result);
                }
            }

       // Set bid status to decrypted
            Bid storage bidData = bids[lotId_][bidId];
            bidData.status = BidStatus.Decrypted;

          if (amountOut > 0 && amountOut >= minBidSize) { 
```
As we can see from the function above, If the bid data comes corrupted during the decryption process, it is basically skipped from consideration in the function, given the absence of a verification procedure designed to ensure data integrity upon decryption or a relevant action/event to trigger if the function finds a corrupted bid when decrypting it.

Consider the following simple scenario:

1. Alice submits an encrypted bid containing errors or corrupted data. Alice cannot be aware of these errors, specially if encryption process produces an output even with invalid data, she can only know this until decryption and no further operation can be done until it reaches the function of `decryptAndSortBids()` during auction settlement. Additionally, she does not have the proper tools from the protocol to ensure that her data will be correctly validated upon decryption (meaning encryption and decryption were successful) or if a notification or event will occur in case the protocol finds an error in her bid upon decryption.
2. When decrypting the bids using the `decryptAndSortBids()` function, any corrupted encrypted bids will be just ignored. Consequently, since Alice's bid is having invalid data, it will not progress further in the auction settlement. According to the documentation a refund is expected and Alice can claim that, however her participation in the auction is not guaranteed even if placing a bid with correct parameters and in time, simply because her bid might be corrupted when applying the encryption or decryption due to the lack of data integrity verifications and the lack of an error handling method if decryption fails. 

## Impact

Due to the absence of integrity verifications / error handling when decrypting bids, there exists the possibility that legitimate bids may become skipped (therefore ghosted by the protocol) compromising the transparency of the auction process. This occurs as the encrypted bids, when stored on-chain, may be subject to potential corruption upon decryption something that protocol must acknowledge in order to implement an error handling procedure when calling the `decryptAndSortBids()` function.

## Code Snippet

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol#L441-L522

## Tool used

Manual Review

## Recommendation

Please ensure to include a try/catch block when decrypting bids within the `decryptAndSortBids()` function. Given the potential for the decryption process to fail, it's crucial to have error handling in place to notify both the protocol and the user promptly.

**Comment by fvelazquez-X** [comment]
Escalate 

Please kindly reassess this finding.

While it is acknowledged that ensuring integrity without the decryption key is impractical, the scenario I highlighted primarily concerns the validation of data upon decryption.

In this context, I was illustrating a scenario where a bidder could submit an encrypted bid that might fail upon decryption—a circumstance not addressed by the `decryptAndSortBids()` function and entirely feasible within the current implementation.

For example, if an adversary submits a manipulated public key containing coordinates deemed valid by the library but greater than the field, the `decryptAndSortBids()` function would fail, and there exists no error-handling mechanism within either the ECIES.sol library or this function to handle this type of situations currently.

And of course this is only an example, it might not be assumed (specially when mixing off chain, on chain scenarios and with a gas intensive operation like decryption) that an error might not appear, and skipping it is not an appropriate way to handle because the realiabilty of the protocol operations is not assured. 

Thank you very much and 
Kind Regards,

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> Please kindly reassess this finding.
> 
> While it is acknowledged that ensuring integrity without the decryption key is impractical, the scenario I highlighted primarily concerns the validation of data upon decryption.
> 
> In this context, I was illustrating a scenario where a bidder could submit an encrypted bid that might fail upon decryption—a circumstance not addressed by the `decryptAndSortBids()` function and entirely feasible within the current implementation.
> 
> For example, if an adversary submits a manipulated public key containing coordinates deemed valid by the library but greater than the field, the `decryptAndSortBids()` function would fail, and there exists no error-handling mechanism within either the ECIES.sol library or this function to handle this type of situations currently.
> 
> And of course this is only an example, it might not be assumed (specially when mixing off chain, on chain scenarios and with a gas intensive operation like decryption) that an error might not appear, and skipping it is not an appropriate way to handle because the realiabilty of the protocol operations is not assured. 
> 
> Thank you very much and 
> Kind Regards, 
> 
> 
> 
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
The following is pointing to user input error, 

> Alice submits an encrypted bid containing errors or corrupted data. Alice cannot be aware of these errors, specially if encryption process produces an output even with invalid data,

and thus is invalid based on the following sherlock [rule](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid)

> 4. User input validation: User input validation to prevent user mistakes is not considered a valid issue.

**Comment by fvelazquez-X** [comment]
Hello @nevillehuang 

I gave an explanation upon decryption but you decided to highlight the part where I just begin the scenario without giving more context. Please I kindly ask you to review it. If you are pointing out input validation, there is valid finding where you can put incorrect elliptic curves and that was accepted. This is completely related to this finding. 

If my finding is invalid then that one automatically is also.

**Comment by Evert0x** [comment]
Planning to reject escalation and keep issue state as is

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [fvelazquez-x](https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/17/#issuecomment-2045630810): rejected
