### ISSUE TITLE
hash - Overly restrictive check for claimBid function disallows bidder's from claiming

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-axis-finance-judging#188]
hash

high

# Overly restrictive check for claimBid function disallows bidder's from claiming

## Summary
Bids can be claimed only when the auction status is Settled although it should be allowed even when the status is Claimed

## Vulnerability Detail

The claimBids function internally calls `_revertIfLotNotSettled` which will revert in case the auction status is not ``
```solidity
    function claimBids(
        uint96 lotId_,
        uint64[] calldata bidIds_
    )
        external
        override
        onlyInternal
        returns (BidClaim[] memory bidClaims, bytes memory auctionOutput)
    {
        // Standard validation
        _revertIfLotInvalid(lotId_);
        _revertIfLotNotSettled(lotId_);


        // Call implementation-specific logic
        return _claimBids(lotId_, bidIds_);
```

```solidity
    function _revertIfLotNotSettled(uint96 lotId_) internal view override {
        // Auction must be settled
        if (auctionData[lotId_].status != Auction.Status.Settled) {
            revert Auction_WrongState(lotId_);
        }
```

This is overrly restrictive as the status can be changed to `Claimed` when the seller claims the proceeds and the bidders should be allowed to claim their payouts even after

```solidity
    function _claimProceeds(uint96 lotId_)
        internal
        override
        returns (uint96 purchased, uint96 sold, uint96 payoutSent)
    {
        // Update the status
        auctionData[lotId_].status = Auction.Status.Claimed;


        // Get the lot data
        Lot memory lot = lotData[lotId_];


        // Return the required data
        return (lot.purchased, lot.sold, lot.partialPayout);
    }
```

## Impact

Bidder's won't be able to claim their payouts

## Code Snippet

claimBids reverts if the status is not Settled
https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/modules/auctions/EMPAM.sol#L902-L906

claiming proceeds sets status to claimed
https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/modules/auctions/EMPAM.sol#L840-L853

## Tool used

Manual Review

## Recommendation

Allow both `Settled` and `Claimed` statuses

Duplicate of #67

**Comment by Oighty** [comment]
Duplicate of #18
