### ISSUE TITLE
hash - Inconsistent timestamp usage across `_revertIfLotActive` and `_revertIfLotConcluded`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-axis-finance-judging#189]
hash

medium

# Inconsistent timestamp usage across `_revertIfLotActive` and `_revertIfLotConcluded`

## Summary
Inconsistent timestamp usage across `_revertIfLotActive` and `_revertIfLotConcluded`

## Vulnerability Detail

At timestmap `lotData[lotId_].conclusion`, the auction is considered not active (ie.concluded) by `_revertIfLotActive` function while `_revertIfLotConcluded` considers the auction as not concluded

```solidity
    function _revertIfLotActive(uint96 lotId_) internal view override {
        if (
            auctionData[lotId_].status == Auction.Status.Created
                && lotData[lotId_].start <= block.timestamp
                && lotData[lotId_].conclusion > block.timestamp
        ) revert Auction_WrongState(lotId_);
    }
```

```solidity
    function _revertIfLotConcluded(uint96 lotId_) internal view virtual {
        // Beyond the conclusion time
        if (lotData[lotId_].conclusion < uint48(block.timestamp)) {
            revert Auction_MarketNotActive(lotId_);
        }

        // Capacity is sold-out, or cancelled
        if (lotData[lotId_].capacity == 0) revert Auction_MarketNotActive(lotId_);
    }
```

This allows for a variety of attacks since both these functions are used in conjunction to avoid many invalid flows:

### Example
1. User's can refund a bid after decryption: 
```solidity
    function refundBid(
        uint96 lotId_,
        uint64 bidId_,
        address caller_
    ) external override onlyInternal returns (uint96 refund) {
        // Standard validation
        _revertIfLotInvalid(lotId_);
        _revertIfBeforeLotStart(lotId_);
        _revertIfBidInvalid(lotId_, bidId_);
        _revertIfNotBidOwner(lotId_, bidId_, caller_);
        _revertIfBidClaimed(lotId_, bidId_);
=>      _revertIfLotConcluded(lotId_);


        // Call implementation-specific logic
        return _refundBid(lotId_, bidId_, caller_);
    }
```

```solidity
    function submitPrivateKey(uint96 lotId_, uint256 privateKey_, uint64 num_) external {
        // Validation
        _revertIfLotInvalid(lotId_);
=>      _revertIfLotActive(lotId_);
        _revertIfBeforeLotStart(lotId_);

        ....

        // Decrypt and sort bids
        _decryptAndSortBids(lotId_, num_);
    }
```

Since `_revertIfLotActive` is used, it is possible to submit the private key and decrypt the bids at `lotData[lotId_].conclusion`. Following this a user can refund one of the bids that has already been decrypted. This will cause multiple issues like the funds being taken back by the bidder while the same fund will be allocated to the seller leading to lost asset for the seller, bricking of decryption processes by refunding multiple bids such that the bids.length becomes less than nextDecryptIndex etc.

2. Seller can cancel EMPAM making bidders loose their assets:
EMPAM auctions are not supposed to be cancellable once started. But the timestamp issue above allows to cancel auctions at `lotData[lotId_].conclusion` which will disable bidder's from withdrawing their assets (linked with the status == SETTLED vulnerability) or make them have wasted keeping their assets in bid

## Impact

Possible bricked decryption, lost assets for the seller / bidder if a block is produced at lotConclusion

## Code Snippet

submit private key
https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/modules/auctions/EMPAM.sol#L400-L420

refundBid
https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/modules/Auction.sol#L501-L516

_revertIfLotConcluded
https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/modules/Auction.sol#L733-L741

_revertIfLotActive
https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/modules/auctions/EMPAM.sol#L885-L891

## Tool used

Manual Review

## Recommendation

Align conclusion timestamps across these functions

Duplicate of #66

**Comment by Oighty** [comment]
Duplicate of #39
