### ISSUE TITLE
web3tycoon - When `Seller` or `AuctionHouse` calls `ClaimBids` they will pay the `Bidders` whom had called `Refund` earlier.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-axis-finance-judging#191]
web3tycoon

high

# When `Seller` or `AuctionHouse` calls `ClaimBids` they will pay the `Bidders` whom had called `Refund` earlier.

## Summary

When `ClaimBids` is called on a `batch` auction. `Bidders` who called refund earlier will recieve free `baseTokens`. 
## Vulnerability Detail
Place this unit test in moonraker/test/AuctionHouse/claimBids.t.sol.
```javascript
    function test_frontRunsClaimBids()
        external
        whenAuctionTypeIsBatch
        whenBatchAuctionModuleIsInstalled
        givenSellerHasBaseTokenBalance(_LOT_CAPACITY)
        givenSellerHasBaseTokenAllowance(_LOT_CAPACITY)
        givenLotIsCreated
        givenLotHasStarted
        givenBalancesAreSet
        givenBidderTwoHasQuoteTokenBalance(_scaleQuoteTokenAmount(_BID_AMOUNT))
        givenBidderTwoHasQuoteTokenAllowance(
            _scaleQuoteTokenAmount(_BID_AMOUNT)
        )
        givenBidCreated(_BIDDER_TWO, _scaleQuoteTokenAmount(_BID_AMOUNT), "")
        givenPayoutIsSet(
            _BIDDER_TWO,
            _REFERRER,
            _scaleQuoteTokenAmount(_BID_AMOUNT),
            _scaleBaseTokenAmount(_BID_AMOUNT_OUT)
        )

        givenMockClaimBidIsSet
    {
        // The user calls refund to receive back the quoteTokens.
        vm.prank(_BIDDER_TWO);
        _auctionHouse.refundBid(_lotId, _bidId);
        // The auction ends
        vm.warp(_startTime + _duration + 1);

        // upon claiming Bids the code sends free base tokens to the bidders.
        vm.prank(address(this));
        _auctionHouse.claimBids(_lotId, _bidIds);

        uint256 aliceQuoteBalance = _quoteToken.balanceOf(_BIDDER_TWO);
        uint256 aliceBaseBalance = _baseToken.balanceOf(_BIDDER_TWO);
        console.log(
            aliceQuoteBalance,
            aliceBaseBalance,
            "They received both their own quoteTokens back and free baseTokens"
        );
    }
```

## Impact
This will lead to the seller losing tokens.

## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L419
This line loads up even the refunded bids

## Tool used

Manual Review

## Recommendation
1. Refactor the code so that the bidders who already refunded will not get free tokens

**Comment by 0xJem** [comment]
The submitter has written a test using a mock batch auction module, which clearly does not handle this scenario (and is out of scope).

The EMP auction module (which is in scope), sets the status of a bid after refund, which in turn prevents future refunds. See the `test_bidAlreadyRefunded_reverts` test case.

**Comment by bennymunyiri** [comment]
in `test_bidAlreadyRefunded_reverts` its calling refund `twice` which going to fail, but in this case is `refund` then `claimbids`. which will bring the vulnerbility.
