### ISSUE TITLE
FindEverythingX - Protocol can face permanent locked funds within EMPAM auction due to revert of mint call (derivative)

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-axis-finance-judging#194]
FindEverythingX

high

# Protocol can face permanent locked funds within EMPAM auction due to revert of mint call (derivative)

## Summary

Protocol can face permanent locked funds within EMPAM auction due to revert of mint call (derivative)

## Vulnerability Detail

Contract: AuctionHouse.sol

First of all, it is important to understand the connection between the Derivative module (LinearVesting) and the AuctionHouse module. Trivially explained, a seller creator can create an auction which pays out the BASE token OR a derivative of the BASE token. 

In the first scenario, everything is perfectly fine.

Now let’s describe the second scenario: Either for FPAM or EMPAM, the core idea is the same: 

When a payout happens via _sendPayout function and the auction is created with a derivative module, this will invoke the mint function on the module instead of directly transferring the payout token to the buyer.

Whenever an auction is created, the params for the derivative are validated:

[https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/bases/Auctioneer.sol#L232](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/bases/Auctioneer.sol#L232)

This includes basic checks such as ensuring the expiry timestamp is not in the past and that the expiry date is larger than the start date. Note how at this point only this basic validation is happening the block.timestamp is at the creation of the auction.

To further illustrate the problem here, we focus solely on the EMPAM module where the impact of this issue is destructive. 

By now we already know the basic flow of the EMPAM module and can confirm that the _sendPayout function is invoked on the following occasions:

a) claimBids: Whenever users claim their confirmed bids
b) settle: Whenever a bid is partially filled or the curator receives a payout.

Now let’s take a look at the flow whenever the auction incorporates a derivative module:

[https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L823](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L823)

We can see here that the Base token is approved to the Derivative module and the mint function is invoked. Please remember by now the basic validation at the auction creation time, which ensured that the expiry time is in the future. 

We now acknowledge that the EMPAM module stays quite some time in the bidding and decryption process, this means the block.timestamp increased by a lot but the expiry timestamp is still the same (of course it is because this was set upon auction creation). 

This will face us to an issue: 

[https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/derivatives/LinearVesting.sol#L262](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/derivatives/LinearVesting.sol#L262)

As highlighted, the “mint” call will execute the same basic validation as in the auction creation with the same expiry timestamp. However, as mentioned, the block.timestamp has increased by a lot, due to the auction being active, obviously. 

This means that the mint call will revert if the block.timestamp is now larger than the expiry time, which will happen for some auctions with a guarantee.

This will then mean we have two issues:

a) Potential DoS of the settle function -> permanent locking of all funds within the AuctionHouse module
b) Potential DoS of individual claim functions -> permanent locking of the unclaimed bids after the block.timestamp has exceeded the expiry time.

## Impact

Impact:

a) Permanent locked/lost funds.

## Code Snippet

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/bases/Auctioneer.sol#L232

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L823

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/derivatives/LinearVesting.sol#L262

## Tool used

Manual Review

## Recommendation

The problem with this issue is that there is no trivial fix. This means even if we ensure that expiry is way larger than the auction conclusion time, this could mean we have a successful settlement and time-sensitive users could claim their bids. 

However, this is no guarantee for users that cannot claim their bids on time because if they claim (lets say a few weeks later), this could mean that the expiry time has already surpassed and then revert in the mint call.

A possible solution would be to adjust the mint function to allow mint calls even after expiry time. However, such a change would need to be carefully checked for side-effects

Duplicate of #178

**Comment by 0xJem** [comment]
Duplicate of https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/178
