### ISSUE TITLE
hash - Protocol fees will be collected even when protocol fee is set to 0

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-axis-finance-judging#199]
hash

medium

# Protocol fees will be collected even when protocol fee is set to 0

## Summary
Protocol fees will be collected even when protocol fee is set to 0

## Vulnerability Detail

In case the protocolFee is set to 0 while the referrer fee is non-zero, no fees should be collected when there is no referrer associated. But the current implementation handles this scenario incorrectly and will collect the referrer fee even in case there is no referrer

```solidity
    function calculateQuoteFees(
        uint96 protocolFee_,
        uint96 referrerFee_,
        bool hasReferrer_,
        uint96 amount_
    ) public pure returns (uint96 toReferrer, uint96 toProtocol) {
        uint96 feeDecimals = uint96(_FEE_DECIMALS);


        if (hasReferrer_) {
            toReferrer = uint96(Math.mulDivDown(amount_, referrerFee_, feeDecimals));
            toProtocol = uint96(Math.mulDivDown(amount_, protocolFee_ + referrerFee_, feeDecimals))
                - toReferrer;
        } else {
            // @audit even if protocol fee is set to 0 and there is no referrer, fees is still captured for the protocol
+>          toProtocol = uint96(Math.mulDivDown(amount_, protocolFee_ + referrerFee_, feeDecimals));
        }
    }
```

## Impact

Fees will be collected incorrectly

## Code Snippet

https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/bases/FeeManager.sol#L68-L87

## Tool used

Manual Review

## Recommendation

Update the else condition to `else if(protocolFee_ != 0)`

**Comment by Oighty** [comment]
This is by design. Due to the way fees are estimated/calculated on batch auctions, we need a consistent fee taken across each bid. It is impractical to iterate through all the bids to get the fees. Therefore, by giving the referrer fee to the protocol when there is no referrer, we guarantee that the same fee will be paid by all bids.
