### ISSUE TITLE
FindEverythingX - Unclaimed bids will never allocate fees to the protocol/referrer

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-axis-finance-judging#200]
FindEverythingX

medium

# Unclaimed bids will never allocate fees to the protocol/referrer

## Summary
Unclaimed bids will never allocate fees to the protocol/referrer

## Vulnerability Detail
Contract: AuctionHouse.sol

Within the EMPAM auction flow, there are fees which are denominated in the quote token. 
These are distributed amongst a potential referrer and the protocol. If the bidder has no referrer, these fees are fully allocated towards the protocol.

After the auction has been settled, the creator can invoke the claimProceeds function which then will pay him out all quote tokens that have been provided (deducted by the fee):

[https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L589](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L589)

Additionally, the function handles a potential refund if the auction was not fully matched. However, that is not important for us right now. 

What is important, is that at this step, the fees just sit in the contract, these will only be allocated if the bidders actually claim their payout (or during the partial fill logic within settle beforehand). 
This is done in such a manner, that the amount actually matches the total aggregated payout:

[https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L427](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L427)

The problem hereby is that these fees are only allocated whenever a user claims their bid. In such a scenario where users do not claim their payout, these fees will never be allocated. 

But the auction has already concluded and the seller already “paid the fee” (by not receiving the full amount of quote tokens). 
Additionally, the purchased amount is clear and won’t change anymore, so there is absolutely no need to wait for allocating them until users invoke the claimBids function. (Remember, the fees are solely based on the purchased amount “the quote tokens”). There are several legit scenarios where users might not claim their bids, such as lost private keys or if they simply forgot the allocation. 

Interestingly, the following comment is made:

“// Fees are not allocated until the user claims their payout so that we don't have to iterate through them here 

This comment is however inaccurate, as there is no need to “iterate” whatsoever, the “purchased” amount will never change because users have already transferred tokens in and the auction is settled, which means there is absolutely no refund possibility. It is also clear that the aggregate of all bidClaim.paid amounts:

[https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/Auction.sol#L609](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/Auction.sol#L609)

[https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L433](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L433)

is exactly the purchased amount:

[https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L589](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L589)

This means in such a scenario, the protocol/referrer will never get the fee allocation, which can become a real problem if the fee is somewhat mentionable and if this happens more often.

The good thing is that there is a very trivial fix for that issue

## Impact
IMPACT: 

a) Permanent locked/lost protocol/referrer fees

## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L589
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L427
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/Auction.sol#L609
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L433
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L589

## Tool used

Manual Review

## Recommendation
I recommend simply allocating the fee directly when the owner withdraws the quote tokens. This seems to be do-able without any negative side-effects, as from what I can observe now, there is no benefit to wait until users have claimed their base tokens.

**Comment by 0xJem** [comment]
Different bids can have different referrers, which means that iteration of every successful bid would be required in order to pre-allocate fees within claimProceeds or anywhere outside of an individual bid claim. This could be prohibitively expensive in large auction lots.

The current design mitigates this.
