### ISSUE TITLE
FindEverythingX - Silent overflow within _settle will result in a loss for the auction creator

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-axis-finance-judging#211]
FindEverythingX

high

# Silent overflow within _settle will result in a loss for the auction creator

## Summary
Silent overflow within _settle will result in a loss for the auction creator

## Vulnerability Detail
CONTRACT: EMPAM.sol

The result.totalAmountIn is denominated as uint256 and increased by every iteration when a bid is matched:

[https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol#L680](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol#L680)

The possibility exists that this will exceed uint96, which is no problem at the mentioned code snippet (as this is a uint256). 

A problem however is the unsafe casting to uint96 in the _settle function:

[https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol#L825](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol#L825)

(it is even indicated by the comments)

If the totalAmountIn is >uint96, this will result in an overflow. 

This value: 

“settlement_.totalIn”

is then used to determine how much was overall purchased: 

[https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/Auction.sol#L609](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/Auction.sol#L609)

Which is then used to determine the payout for the seller:

[https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol#L852](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol#L852)

[https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/Auction.sol#L653](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/Auction.sol#L653)

[https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L578](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L578)

[https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L593](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L593)

[https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L600](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L600)

The seller will therefore receive almost no tokens/less tokens (depending on the size of the overflow)

Additionally, the fees are also calculated based on this amount:

[https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L589](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L589)

It is clear that this will not most likely not happen for tokens with a value > 1 USD, since uint96 is around 79.2 billion tokens. 

However, for very cheap tokens it can definitely happen that the total valid bidding amount is larger.

## Impact
IMPACT:

a) Loss of funds for seller

## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol#L680
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol#L825
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/Auction.sol#L609
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol#L852
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/Auction.sol#L653
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L578
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L593
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L600
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L589

## Tool used

Manual Review

## Recommendation
Consider removing the unsafe uint96 casting.

Duplicate of #181

**Comment by 0xJem** [comment]
Duplicate of https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/34
