### ISSUE TITLE
sl1 - `_isLess()` function of `MaxPriorityQueue` incorrectly determines the ordering of bids.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-axis-finance-judging#217]
sl1

high

# `_isLess()` function of `MaxPriorityQueue` incorrectly determines the ordering of bids.

## Summary
`MaxPriorityQueue` is used to store decrypted bids in a descending order. This queue will be used during an auction settlement to determine the winnings bids. The problem is that the `_isLess()` helper function of the `MaxPriorityQueue` will incorrectly determine the ordering of bids.
## Vulnerability Detail
[MaxPriorityQueue.sol#L109-L120](https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/lib/MaxPriorityQueue.sol#L109-L120)
```solidity
///@notice helper function to determine ordering. When two bids have the same price, give priority
///to the lower bid ID (inserted earlier)
function _isLess(
    Queue storage self,
    uint256 i,
    uint256 j
) private view returns (bool) {
    uint64 iId = self.bidIdList[i];
    uint64 jId = self.bidIdList[j];
    Bid memory bidI = self.idToBidMap[iId];
    Bid memory bidJ = self.idToBidMap[jId];
    uint256 relI = uint256(bidI.amountIn) * uint256(bidJ.minAmountOut);
    uint256 relJ = uint256(bidJ.amountIn) * uint256(bidI.minAmountOut);
    if (relI == relJ) {
        return iId > jId;
    }
    return relI < relJ;
}
```
As can be implied from the comment, when two bids have the same price, the function should give priority to the lower bid ID. The problem is that it does not actually calculate the price of said bids, thus the ordering can be wrong.

It's important to note that the price is calculated as: `amountIn / amountOut`, which can be seen in the `_claimBids()` function of the EMPAM auction module.

[EMPAM.sol#L335-L339](https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/modules/auctions/EMPAM.sol#L335-L339)
```solidity
uint96 price = uint96(
    bidData.minAmountOut == 0
        ? 0
        : Math.mulDivUp(
            uint256(bidData.amount),
            baseScale,
            uint256(bidData.minAmountOut)
        )
);
```
The `_isLess()` function uses these calculations to determine the ordering without taking the actual price into account:
```solidity
uint256 relI = uint256(bidI.amountIn) * uint256(bidJ.minAmountOut);
uint256 relJ = uint256(bidJ.amountIn) * uint256(bidI.minAmountOut);
```

Let's assume the case:
```md
Bid1:
  * AmountIn = 2 quoteTokens
  * AmountOut = 4 baseTokens
  Price = 2 / 4 = 0.5 quoteTokens for 1 baseToken
Bid2:
  * AmountIn = 4 quoteTokens
  * AmountOut = 2 baseTokens
  Price = 4 / 2 = 2 quoteTokens for 1 baseToken

Clearly the bid 2 has higher price, thus it should be first in the the queue of decryptedBids

But _isLess()  function determines the ordering wrong:

relI = 2 * 4 = 8
relJ = 4 * 2 = 8
Since relI == relJ, _isLess() function will give priority to the lower bidId, 
which will be bid1. So while bid1 clearly has lesser price than bid2, 
it will be positioned first in the queue, because of the lower bidId.
```
## Impact
Disruption of the normal flow of the auction, leading to bids with lesser price being filled first.
## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/lib/MaxPriorityQueue.sol#L109-L120
## Tool used

Manual Review

## Recommendation
`_isLess()` function should calculate the price of the bid and determine the ordering based on that.

Duplicate of #226

**Comment by Oighty** [comment]
Your example is wrong. 
It would be
```
relI = 2 * 2 = 4
relJ = 4 * 4 = 16;
```
Therefore `relI < relJ` is true and `bid1` is less than `bid2` as it should be.

Duplicate of #226
