### ISSUE TITLE
AuditorPraise - `Auctioneer._isLotValid()`  will always cause revert for most recent auction lot id.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-axis-finance-judging#22]
AuditorPraise

high

# `Auctioneer._isLotValid()`  will always cause revert for most recent auction lot id.

## Summary
`Auctioneer._isLotValid()` is faulty
## Vulnerability Detail
```solidity
 function _isLotValid(uint96 lotId_) internal view {
        if (lotId_ >= lotCounter) revert InvalidLotId(lotId_);// @audit-issue something feels off
    }
```
According to the if statement within `Auctioneer._isLotValid()` above, if lotId == lotCounter there will be a revert

The issue here is that the most recent auction lot id will be == lotCounter because in `Auctioneer.auction()` when the lotId is being set, it is ==  lotCounter
```solidity
 // Increment lot count and get ID
            lotId = lotCounter++;
```
This affects cancel(), getModuleForId() in Auctioneer.sol and purchase(), bid(), refundBid(), claimBids(), settle(), claimProceeds() and curate() in AuctionHouse.sol

## Impact
`Auctioneer._isLotValid()`  will always cause revert for most recent auction lot id.
## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/bases/Auctioneer.sol#L403
## Tool used

Manual Review

## Recommendation
change this:
```solidity
       if (lotId_ >= lotCounter) revert InvalidLotId(lotId_)
```
to this:
```solidity
       if (lotId_ > lotCounter) revert InvalidLotId(lotId_)
```

**Comment by Oighty** [comment]
I think this report misunderstands how the post-fix operator (`x++`) works.
```
lotId = lotCounter++;
```
Specifically, this statement:
1. Sets `lotId` to the current value of `lotCounter`
2. Increments `lotCounter` by 1.

Therefore, after the operation, `lotId` is 1 less than `lotCounter`.
