### ISSUE TITLE
hash - No setter for minAuctionDuration

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-axis-finance-judging#224]
hash

medium

# No setter for minAuctionDuration

## Summary
No setter for minAuctionDuration

## Vulnerability Detail

The `minAuctionDuration` parameters lacks setter functions

```solidity
    uint48 public minAuctionDuration;
```
```solidity
    constructor(address auctionHouse_) AuctionModule(auctionHouse_) {
        // Set the minimum auction duration to 1 day initially
        minAuctionDuration = 1 days;
    }
```

## Impact

minAuctionDuration cannot be updated and hence the protocol is stuck with the same duration unless an upgrade is made

## Code Snippet

https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/modules/auctions/FPAM.sol#L47-L50

## Tool used

Manual Review

## Recommendation

Add a function to set `minAuctionDuration`

**Comment by AtanasDimulski** [comment]
Escalate,

As @nevillehuang has mentioned there is no core functionality broken at all, + the protocol can always deploy a new version of the module if needed. This issue is low/info. Realistically it is hard to imagine that someone will want to create an auction that is less than a day.

**Comment by sherlock-admin2** [comment]
> Escalate,
> 
> As @nevillehuang has mentioned there is no core functionality broken at all, + the protocol can always deploy a new version of the module if needed. This issue is low/info. Realistically it is hard to imagine that someone will want to create an auction that is less than a day. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
Agree with escalation as per this discussion [here](https://discord.com/channels/812037309376495636/1219314589506994307/1227422885594009662) and [here](https://discord.com/channels/812037309376495636/1219314589506994307/1227504993846693888)

Edit: Just wanted to note that upgrades are never a solution to intended direct code logic fix, although it is true no core functionality is broken here.

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Axis-Fi/moonraker/pull/117

**Comment by Evert0x** [comment]
Planning to accept escalation and invalidate issue

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [AtanasDimulski](https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/224/#issuecomment-2047131509): accepted

**Comment by 10xhash** [comment]
> The protocol team fixed this issue in the following PRs/commits: [Axis-Fi/moonraker#117](https://github.com/Axis-Fi/moonraker/pull/117)

Fixed
Added setter function

**Comment by sherlock-admin4** [comment]
The Lead Senior Watson signed off on the fix.
