### ISSUE TITLE
novaman33 - Some tokens will cause DOS of claimProceeds function

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-axis-finance-judging#31]
novaman33

high

# Some tokens will cause DOS of claimProceeds function

## Summary
In the `claimProceeds` function, there is a transfer that gives the prefunded amount that was not sold back to the seller. However in most cases, the prefunded amount will be 0 causing the transfer to refund for some tokens which do not support 0 transfers(e.g. LEND). 
## Vulnerability Detail
In the claimProceeds function there is no check if the transfer amount is going to be zero:
https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/AuctionHouse.sol#L608
If the base token is LEND or any other token that does not support the zero transfer - the claimProceeds will function revert, declining the seller their profit for the current lot, if the prefunding refund is greater than zero which will be a very usual case.
## Impact
The seller will never claim their profit and the tokens will be stuck forever in the contract - High.
## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/AuctionHouse.sol#L608
## Tool used

Manual Review

## Recommendation
Check if the prefundedRefund is greater than zero before executing the transfer.

Duplicate of #21

**Comment by Oighty** [comment]
Duplicate of #21
