### ISSUE TITLE
pseudoArtist - `EMPAM.sol::_settle()`  `settlement_.totalIn` will silently overflow

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-axis-finance-judging#34]
pseudoArtist

medium

# `EMPAM.sol::_settle()`  `settlement_.totalIn` will silently overflow

## Summary
While calling the function [_settle()](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol#L747-L837) , it will overflow
## Vulnerability Detail
[_settle()](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol#L747-L837) in EMPAM.sol, there is calculation of [settlement_.totalIn](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol#L825) on L825 which is of `uint96`  ` settlement_.totalIn = uint96(result.totalAmountIn)` , While the `totalAmountIn` is of `uint256` type, Typecasting uint256 into uint96 will lead to silent overflow.
## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol#L825
## Tool used

Manual Review

## Recommendation
```diff solidity
 struct MarginalPriceResult {
        uint96 marginalPrice;
        uint64 marginalBidId;
        uint64 partialFillBidId;
-        uint256 totalAmountIn;
        uint256 capacityExpended;
    }
 struct MarginalPriceResult {
        uint96 marginalPrice;
        uint64 marginalBidId;
        uint64 partialFillBidId;
+      uint96 totalAmountIn;
        uint256 capacityExpended;
    }
   ```

Duplicate of #181

**Comment by 0xJem** [comment]
This is valid
