### ISSUE TITLE
poslednaya - Lack of upgradability of singleton `AuctionHouse` can result in redeploy entire system

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-axis-finance-judging#51]
poslednaya

high

# Lack of upgradability of singleton `AuctionHouse` can result in redeploy entire system

## Summary
Incorrect lack of upgradability can lead to redeploy whole system if bug will be in `AuctionHouse` contract. 

## Vulnerability Detail
Looks like team want to combine benefits from modularity of `Default Framework` and singleton of `SeaPort`. 

In `Default Framework` there is `_migrateKernel()` function. When we need correct/implement new version of main contract (AuctionHouse/Kernel) we can use it to save modules alive. Otherwise modules will not work due to `onlyParent(address(AuctionHouse))` modifier on functions. 

Looks like the Axis team deliberately abandoned this feature, but it is mistake. Users should still trust to modules just because all main logic/storage of lots are there. And modules are upgradable in versions by the owner, so it is not about trustless. 

`OpenSea` core singleton contract `Seaport` has versions [1.1-1.6](https://github.com/ProjectOpenSea/seaport). And they can save modules alive through the versions of singleton just passing addresses into new implementation. But in our case we can't because `onlyParent` modifier on modules. 

Deployment singleton under the proxy and look to avoid storage collisions in singleton contract through the versions without names spaced slots also not a so safe idea. 

Choosing not to implement `_migrateKernel()` or corresponding functions on modules to change `Parent` address lead to lack of upgradability without benefits. 

## Impact
Any even little bug in `AuctionHouse` singleton will break the entire protocol, including modules. And lead to redeploy whole system, what can affect user trust. 

## Code Snippet

```solidity
    modifier onlyParent() {
        if (msg.sender != PARENT) revert Module_OnlyParent(msg.sender);
        _;
    }
```

In `Default Framework`: https://github.com/fullyallocated/Default/blob/ca9a2c47b7251fc8e9c3254a398ad784306f2f8e/src/Kernel.sol#L306

In `OlympusDAO`: https://github.com/OlympusDAO/olympus-v3/blob/19236eb1c02464df8fb79c7b59b7195d7511b338/src/Kernel.sol#L338C14-L338C28

## Tool used

Manual Review

## Recommendation
Consider adding `_migrateKernel()` or corresponding function in `Module` to change `Parent` with subsequent execution via `execOnModule()`.

**Comment by 0xJem** [comment]
This is deliberate. It was decided that to prevent upgrades in order to mitigate attacks and reduce gas costs.

If there's a bug in the AuctionHouse, a new AuctionHouse can be deployed and future auction lots will use that.
