### ISSUE TITLE
cu5t0mPe0 - curator can't get fee

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-axis-finance-judging#58]
cu5t0mPe0

medium

# curator can't get fee

## Summary

The seller can not give the approval permission to the auctionHouse contract, causing the curator call to fail.

## Vulnerability Detail

The curator must first call the `curate` function to obtain the fee, but if the seller does not grant the AuctionHouse contract approve permission, the curate call will fail.

Because curate transfers tokens through transferFrom, this requires approval from the seller.

https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/AuctionHouse.sol#L683-L685

## Impact

curator can't get fee

## Code Snippet

https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/AuctionHouse.sol#L683-L685

## Tool used

Manual Review

## Recommendation

The seller should transfer the curate fee to the contract in advance.

**Comment by Oighty** [comment]
`curate` does require the seller to have approved the contract, but it is assumed they will do so. If for whatever reason, they decide they don't want to work with the curator after they have created the auction, they could revoke the approval to disallow the curator from accepting the curation. This is kind of an edge case, but I don't view it as an issue. The auction will not show up as "curated" by the curator unless they are able to successfully call the curate function.
