### ISSUE TITLE
ether_sky - The priceFor and maxAmountAccepted functions in the Catalogue contract are currently returning incorrect values.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-axis-finance-judging#62]
ether_sky

medium

# The priceFor and maxAmountAccepted functions in the Catalogue contract are currently returning incorrect values.

## Summary
Users can obtain various information by interacting with the functions in the `Catalogue` contract.
However, certain functions currently return incorrect values, which could impact users' decisions.
## Vulnerability Detail
The `priceFor` and `maxAmountAccepted` functions return values that include the associated `fees`.
```solidity
function priceFor(uint96 lotId_, uint96 payout_) external view returns (uint256) {
    uint256 price = module.priceFor(lotId_, payout_);

    // Calculate fee estimate assuming there is a referrer and add to price
    price += _calculateFeeEstimate(keycodeFromVeecode(routing.auctionReference), true, price);
}
```
The `_calculateFeeEstimate ` function should return the `fee` corresponding to this `price`.
However, this function returns the sum of the `price` and `fees`.
```solidity
function _calculateFeeEstimate(
    Keycode auctionType_,
    bool hasReferrer_,
    uint256 price_
) internal view returns (uint256 feeEstimate) {
    // In this case we have to invert the fee calculation
    // We provide a conservative estimate by assuming there is a referrer and rounding up
    (uint48 fee, uint48 referrerFee,) = FeeManager(auctionHouse).fees(auctionType_);
    if (hasReferrer_) fee += referrerFee;

    uint256 numer = price_ * _FEE_DECIMALS;
    uint256 denom = _FEE_DECIMALS - fee;

    return (numer / denom) + ((numer % denom == 0) ? 0 : 1); // round up if necessary
}
```

Although these functions are `view` functions, users can rely on them.
For instance, a user planning to place a `bid` might call the `priceFor` function to determine the required `quote` token amounts for the expected `base` tokens.
Unfortunately, due to the incorrect values returned by this function, a user may decide not to `bid` or `bid` with inaccurate `quote` token amounts.
## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/Catalogue.sol#L83
https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/Catalogue.sol#L147-L150
## Tool used

Manual Review

## Recommendation
```solidity
function _calculateFeeEstimate(
    Keycode auctionType_,
    bool hasReferrer_,
    uint256 price_
) internal view returns (uint256 feeEstimate) {
    // In this case we have to invert the fee calculation
    // We provide a conservative estimate by assuming there is a referrer and rounding up
    (uint48 fee, uint48 referrerFee,) = FeeManager(auctionHouse).fees(auctionType_);
    if (hasReferrer_) fee += referrerFee;

-     uint256 numer = price_ * _FEE_DECIMALS;
+     uint256 numer = price_ * fee;
    uint256 denom = _FEE_DECIMALS - fee;

    return (numer / denom) + ((numer % denom == 0) ? 0 : 1); // round up if necessary
}
```

Duplicate of #128

**Comment by Oighty** [comment]
`priceFor` and `payoutFor` are only meant to be used with Atomic Auctions, which we should clarify. Additionally, because of this, the EMPAM batch auction should revert calls to these functions instead of the current behavior.
