### ISSUE TITLE
enfrasico - WETH address is incorrect, causing loss of WETH yield

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-axis-finance-judging#73]
enfrasico

high

# WETH address is incorrect, causing loss of WETH yield

## Summary
WETH address used is incorrect. `0x4200000000000000000000000000000000000023` is the address for testnet, not mainnet. As a result, the blast auction house cannot actually claim any WETH yield.

## Vulnerability Detail
The correct WETH address for mainnet should be `0x4200000000000000000000000000000000000004`. Use of correct address is paramount, or all yield will be lost.

## Impact
Loss of yield with 100% certainty.

## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/blast/BlastAuctionHouse.sol#L39

## Tool used

Manual Review

## Recommendation
Change the address to `0x4200000000000000000000000000000000000004`.

Duplicate of #91

**Comment by Oighty** [comment]
Acknowledged. We intended to change this for mainnet deployment.
