### ISSUE TITLE
ether_sky - The onCurate callback function may receive incorrect parameters.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-axis-finance-judging#77]
ether_sky

medium

# The onCurate callback function may receive incorrect parameters.

## Summary
The `auction creator` can receive notifications through `callback` functions whenever events occur in an `auction`.
Ensuring the correctness of input parameters for these functions is crucial.
Users can implement their own `callback` functions and perform operations based on these input parameters.
The `onCurate` callback functions is invoked when the `curator` curates the `auction`.
However, there is a potential issue: the `curatorFeePayout` parameter may sometimes be calculated in terms of `quote` tokens, but it should actually be in `base` tokens.
As a result, the `auction creator` may receive incorrect parameters.
## Vulnerability Detail
In the `curate` function, we determine the value of `curatorFeePayout` based on the remaining `capacity`.
```solidity
function curate(uint96 lotId_, bytes calldata callbackData_) external nonReentrant {
   uint96 curatorFeePayout = uint96(
        _calculatePayoutFees(
            feeData.curated, feeData.curatorFee, module.remainingCapacity(lotId_)
        )
    );
}
```
If the `auction` is `prefunded`, we ensure that the `capacity` is in `base` tokens.
Consequently, the `curatorFeePayout` is also calculated in `base` tokens.

However, if the `auction` is not `prefunded` and `capacityInQuote` is `true`, the `capacity` is in `quote` tokens.
As a result, the calculated `curatorFeePayout` is also in `quote` tokens.

Despite the above considerations, the `onCurate` callback function is called with this parameter.
```solidity
function curate(uint96 lotId_, bytes calldata callbackData_) external nonReentrant {
   uint96 curatorFeePayout = uint96(
        _calculatePayoutFees(
            feeData.curated, feeData.curatorFee, module.remainingCapacity(lotId_)
        )
    );
    if (routing.funding > 0) {
    } else {
        // If the auction is not pre-funded, call the onCurate callback
        Callbacks.onCurate(routing.callbacks, lotId_, curatorFeePayout, false, callbackData_);  // @audit, here
    }
}
```
The name `curatorFeePayout` implies that this value should be calculated in `base` tokens, as the `curator fee` represents a portion of `base` tokens.
## Impact
This may result in unintended behavior for users.
## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/AuctionHouse.sol#L655-L659
https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/AuctionHouse.sol#L692-L695
## Tool used

Manual Review

## Recommendation
When `capacityInQuote` is `true`, we should convert the `curatorFeePayout` value to `base` tokens.

**Comment by 0xJem** [comment]
Invalid.

capacityInQuote must be false when prefunding is enabled on an auction.
