### ISSUE TITLE
ether_sky - The auction creator has control over the auction process.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-axis-finance-judging#80]
ether_sky

medium

# The auction creator has control over the auction process.

## Summary
While no one should have control over an ongoing `auction`, the `auction creator`, who possesses the `private key`, can influence the `auction` by decrypting the `bid` information.
Unfortunately, this can result in several undesirable outcomes.
## Vulnerability Detail
During the `auctions`, the `creators` can access and decrypt `bids` using the `private key`.
Consequently, they gain insight into the ongoing `auctions'` status.
The `auction creator` can have several chocies.
1. `Aggressive Bidding`.
If the `creator` believes that `bidders'` prices are insufficient, they can place a `bid` at the highest price.
While this may result in some loss, it allows them to pay `fees` in `quote` tokens while preserving `base` tokens.
`Bidders`, however, can not acquire `base` tokens.
2. `Strategic Bidding`
Alternatively, the `creator` can `bid` at an appropriate price for optimal results.
For instance, consider `bids (q1, p1), (q2, p2), (q3, p3) ...` where `p1 > p2 > p3`.
if `q1 + q2` doesn't fill the `capacity`, the `auction` involves the third `bid`, and the `marginal price` falls to `p3`.
Suppose the `creator` desires `quote` tokens at price `p2`: he can create a `bid` with price `p2` and `quote` tokens to fill the `capacity`.
Consequently, he can acquire `q1 + q2` tokens at price `p2`.
3. `Mitigating Failure`
If `quote` amounts fall short of the required amounts, the `auction` is considered unsuccessful,.
```solidity
function _settle(uint96 lotId_)
    internal
    override
    returns (Settlement memory settlement_, bytes memory auctionOutput_)
{
    if (
        result.capacityExpended >= auctionData[lotId_].minFilled
            && result.marginalPrice >= lotAuctionData.minPrice
    ) { }
}
```
To prevent this, the `auction creator` can create a `bid` with a small amount of `quote` tokens to fill the `auction`.
## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/modules/auctions/EMPAM.sol#L791-L794
## Tool used

Manual Review

## Recommendation
```solidity
- mapping(uint96 lotId => mapping(uint64 bidId => EncryptedBid)) public encryptedBids;
+ mapping(uint96 lotId => mapping(uint64 bidId => EncryptedBid)) private encryptedBids;
```

**Comment by Oighty** [comment]
The key assumption here is that the seller (auction creator) has the private key that corresponds to the public key for the auction, but that doesn't necessarily have to be case. Axis has implemented a key management service that provides a new BN254 public key to a user, stores the private key, and then releases the key to anyone who calls the API after the auction ends. Similarly, multi-party computation (MPC) protocols are being built that could do this in a decentralized way, e.g. Lit Protocol.

I agree that the seller could have the private key and the scenarios you lay out are plausible, but it depends on external factors, including where the key is held. We can't enforce using a key-pair that the seller doesn't have custody of, but we can encourage it through the off-chain tooling we provide for use in auctions.

**Comment by 10xhash** [comment]
Escalate

The owner of the private key will have the ability to decrypt the bids. This is the expected behavior and there is no additional damage done to any other party

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The owner of the private key will have the ability to decrypt the bids. This is the expected behavior and there is no additional damage done to any other party 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by etherSky111** [comment]
The owner of the private key can decrypt the `bids`.
However, he should not be the `auction creator`.
It is really unfair for `bidders` as I described in my report.
This will be direct damage to the `bidders`.

**Comment by nevillehuang** [comment]
@10xhash Could you elaborate more on your escalation:  

> This is the expected behavior and there is no additional damage done to any other party

**Comment by 10xhash** [comment]
> @10xhash Could you elaborate more on your escalation:
> 
> > This is the expected behavior and there is no additional damage done to any other party

Whoever owns the private key will have the ability to know the information about the bids. This is the expected behaviour. The key can either be stored in a key management service or by the auction creator itself. It is up to the bidder's to decide whether to bid on auctions in which the private key is controlled by the creator itself. 

Even if the private key is controlled by the auction creator, there is no significant damage done to the bidder's. All the scenarios mentioned in the report are naturally expected scenarios for the bidder's (ie. having their bids not executed due to a higher priced bid) and could cost the creator unnecessary fees

**Comment by etherSky111** [comment]
How can `bidders` know whether the key is belong to the `auction creator` or not?
And in any case, the `auction` should be fair for `bidders` in the `sealed-bid auction`.
In the doc, we could find below.
```
EMPA is a fully on-chain, sealed-bid, batch auction system built on the Axis Protocol that uses ECIES encryption and a multi-step settlement process to avoid issues of previous sealed bid auction designs
```
And we could easily check what is a `sealed-bid auction`.

Regarding the impact, the above mentioned scenarios should not be allowed in a `sealed-bid auction`.

**Comment by nevillehuang** [comment]
Agree with @etherSky111, similar to issue #174, auction creator should not have an added advantage/power to grief, in this case, a sealed-bid auction where no bidder should know how much the other auction participants have bid.

**Comment by Evert0x** [comment]
I don't believe this is an issue. It's a design choice and the issue isn't present in the smart contract logic, it applies to the business logic. 

Also, the recommendation wouldn't help as `encryptedBids` is still stored on the EVM and can be retrieved. 

Planning to reject escalation and invalidate issue, as escalation doesn't provide the right argument.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [10xhash](https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/80/#issuecomment-2047666714): rejected
